import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="bg-slate-800 text-white px-3 ">
          <ul className="bg-red-400 flex justify-between items-center max-w-[700px] ">
            <div className="flex [&>*]:p-3 [&>*]:hover:bg-slate-700 [&>*]:cursor-pointer">
              <li>Anasayfa</li>
              <li>Kategoriler</li>
            </div>
            <li className="p-3 hover:bg-slate-700 cursor-pointer">
              Kayıt Ol / Giriş yap
            </li>
          </ul>
        </div>
        <div className="flex justify-center min-h-screen  font-[family-name:var(--font-geist-sans)]">
          {children}
        </div>
      </body>
    </html>
  );
}
