import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-emerald-50`}
      >
        <div className="bg-emerald-300">
          <ul className="flex justify-between items-center max-w-[1000px] mx-auto  ">
            <div className="flex [&>*]:py-3 [&>*]:px-4 [&>*]:hover:bg-emerald-400 [&>*]:cursor-pointer">
              <li>
                <Link href="/">Main Page</Link>
              </li>
              <li>
                <Link href="/categories">Categories</Link>
              </li>
              <li>
                <Link href="/create-blog">Create Post</Link>
              </li>
            </div>
            <li className="p-3 hover:bg-emerald-400 cursor-pointer">
              <Link href="/register">Login / Signup</Link>
            </li>
          </ul>
        </div>
        <div className="flex justify-center min-h-screen mt-4 font-[family-name:var(--font-geist-sans)]">
          {children}
        </div>
      </body>
    </html>
  );
}
