import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { i18n, type Locale } from "../../i18n-config";
import Navbar from "@/components/navbar";

import { getDictionary } from "../../get-dictionary";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}) {
  const params = await props.params;

  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-emerald-50`}
      >
        <Navbar dictionary={dictionary.navbar} />
        <div className="flex justify-center min-h-screen mt-4 font-[family-name:var(--font-geist-sans)]">
          {props.children}
        </div>
      </body>
    </html>
  );
}
